### ISSUE TITLE
_Cooked Smoked Tofu_ smoking recipe takes _Smoked Tofu_ as input

### ISSUE THREAD

**Issue by Nemo157** [Player005/VeganDelightFabric#7]
I assume this was meant to take _Cooked Tofu_ as input, similar to the _Cooked Tofu Slices_ → _Cooked Smoked Tofu Slices_ recipe.

**Comment by Player005** [comment]
I have now fixed it in the main repo:
https://github.com/SayWhatSayMon/VeganDelight/commit/036ab80222973f4ef3e9cca74ef718de28df9ed1
(the fabric port has been merged together with the official forge version, this repo will be archived, so please report there if you find any more issues)

Thanks a lot for your report! I don't think we would have noticed this otherwise.
